# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2016-12-10 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_host_hostadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAdmin2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Host')),
                ('c2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.HostAdmin2')),
            ],
        ),
        migrations.AddField(
            model_name='hostadmin2',
            name='host',
            field=models.ManyToManyField(through='app01.HostRelation', to='app01.Host'),
        ),
    ]
